### ISSUE TITLE
nic.dhcp is ignored

### ISSUE THREAD

**Issue by xetys** [profitbricks/terraform-provider-profitbricks#48]
when using

```
  nic {
    lan = "${profitbricks_lan.bootstrap_lan.id}"
    dhcp = false
  }
```

or 

```
resource "profitbricks_nic" "bootstrap_nic1" {
  datacenter_id   = "${profitbricks_datacenter.main.id}"
  server_id       = "${profitbricks_server.bootstrap.id}"
  lan = "${profitbricks_lan.bootstrap_lan.id}"
  dhcp = false
}
```

the real state observable over API and the ProfitBricks UI is DHCP set to true.

**Comment by jasminSPC** [comment]
This has been addressed here #41 and should be available with version[ 1.2.5 ](https://github.com/profitbricks/terraform-provider-profitbricks/releases/tag/v1.2.5)

If you are using profitbricks as builtin provider in Terraform then the patch has not been released yet.

**Comment by xetys** [comment]
I was using the recommended install way, with `go get`. In the Makefile I see version 1.2.5

So the issue still exists to me :/

**Comment by jasminSPC** [comment]
@xetys go get won't install the provider for you. The provider needs to be available in the `$PATH` so probably that's why it isn't working. I just ran this:
```
provider "profitbricks" {
  retries = 100
}

data "profitbricks_location" "loc" {
  name = "karl"
  feature = "SSD"
}

data "profitbricks_image" "test_img" {
  name = "Ubuntu"
  type = "HDD"
  version = "16"
  location = "${data.profitbricks_location.loc.id}"
}

resource "profitbricks_datacenter" "main" {
  name = "datacenter 01"
  location = "${data.profitbricks_location.loc.id}"
  description = "description of the datacenter"
}

//Public lan
resource "profitbricks_lan" "webserver_lan" {
  datacenter_id = "${profitbricks_datacenter.main.id}"
  public = true
  name = "public"
}

//IP Block
resource "profitbricks_ipblock" "webserver_ip" {
  location = "${data.profitbricks_location.loc.id}"
  size = 2
}

resource "profitbricks_server" "webserver" {
  name = "webserver"
  datacenter_id = "${profitbricks_datacenter.main.id}"
  cores = 1
  ram = 1024
  availability_zone = "ZONE_1"
  cpu_family = "AMD_OPTERON"

  volume {
    name = "system"
    image_name = "${data.profitbricks_image.test_img.id}"
    size = 5
    disk_type = "SSD"
    ssh_key_path = [
      "${var.ssh_keys}"]
    availability_zone = "AUTO"
  }

  nic {
    lan = "${profitbricks_lan.webserver_lan.id}"
    dhcp = true
    ip = "${profitbricks_ipblock.webserver_ip.ips.0}"
  }

}

resource "profitbricks_nic" "webserver_nic" {
  datacenter_id = "${profitbricks_datacenter.main.id}"
  server_id = "${profitbricks_server.webserver.id}"
  lan = 2
  dhcp = false
  firewall_active = true
}
```

and I got this afterwards:
```
$ terraform plan example/
[WARN] /Volumes/Data/go/bin/terraform-provider-profitbricks overrides an internal plugin for profitbricks-provider.
  If you did not expect to see this message you will need to remove the old plugin.
  See https://www.terraform.io/docs/internals/internal-plugins.html
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

data.profitbricks_location.loc: Refreshing state...
profitbricks_ipblock.webserver_ip: Refreshing state... (ID: 9b5e3041-fadb-454a-b299-9802d576fc12)
profitbricks_datacenter.main: Refreshing state... (ID: af583c3b-980a-4c28-9198-e9f5b79b6861)
data.profitbricks_image.test_img: Refreshing state...
profitbricks_lan.webserver_lan: Refreshing state... (ID: 1)
profitbricks_server.webserver: Refreshing state... (ID: 7ca0bbc0-9458-44b8-9e97-0b8116f6940d)
profitbricks_nic.webserver_nic: Refreshing state... (ID: 4d50e806-5aab-4521-a9a9-2636f5733dab)
No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, Terraform
doesn't need to do anything.
```

Also this is what my Virtual Datacenter JSON looked like:
```
{
  "id" : "af583c3b-980a-4c28-9198-e9f5b79b6861",
  "type" : "datacenter",
  "href" : "https://api.profitbricks.com/cloudapi/v3/datacenters/af583c3b-980a-4c28-9198-e9f5b79b6861",
  "metadata" : {
    "createdDate" : "2017-06-05T23:09:42Z",
    "createdBy" : "jasmin@stackpointcloud.com",
    "etag" : "32e0dc4547250fccd1b955d6f7a863bf",
    "lastModifiedDate" : "2017-06-05T23:11:28Z",
    "lastModifiedBy" : "jasmin@stackpointcloud.com",
    "state" : "AVAILABLE"
  },
  "properties" : {
    "name" : "datacenter 01",
    "description" : "description of the datacenter",
    "location" : "de/fkb",
    "version" : 4,
    "features" : [ "SSD", "MULTIPLE_CPU" ]
  },
  "entities" : {
    "servers" : {
      "id" : "af583c3b-980a-4c28-9198-e9f5b79b6861/servers",
      "type" : "collection",
      "href" : "https://api.profitbricks.com/cloudapi/v3/datacenters/af583c3b-980a-4c28-9198-e9f5b79b6861/servers",
      "items" : [ {
        "id" : "7ca0bbc0-9458-44b8-9e97-0b8116f6940d",
        "type" : "server",
        "href" : "https://api.profitbricks.com/cloudapi/v3/datacenters/af583c3b-980a-4c28-9198-e9f5b79b6861/servers/7ca0bbc0-9458-44b8-9e97-0b8116f6940d",
        "metadata" : {
          "createdDate" : "2017-06-05T23:09:56Z",
          "createdBy" : "jasmin@stackpointcloud.com",
          "etag" : "32e0dc4547250fccd1b955d6f7a863bf",
          "lastModifiedDate" : "2017-06-05T23:11:28Z",
          "lastModifiedBy" : "jasmin@stackpointcloud.com",
          "state" : "AVAILABLE"
        },
        "properties" : {
          "name" : "webserver",
          "cores" : 1,
          "ram" : 1024,
          "availabilityZone" : "ZONE_1",
          "vmState" : "RUNNING",
          "bootCdrom" : null,
          "bootVolume" : {
            "id" : "7fc9ab59-066d-43e1-99d3-d6d78b15143e",
            "type" : "volume",
            "href" : "https://api.profitbricks.com/cloudapi/v3/datacenters/af583c3b-980a-4c28-9198-e9f5b79b6861/volumes/7fc9ab59-066d-43e1-99d3-d6d78b15143e",
            "metadata" : {
              "createdDate" : "2017-06-05T23:09:56Z",
              "createdBy" : "jasmin@stackpointcloud.com",
              "etag" : "39fed922f2397227d436261f0f75d16c",
              "lastModifiedDate" : "2017-06-05T23:09:56Z",
              "lastModifiedBy" : "jasmin@stackpointcloud.com",
              "state" : "AVAILABLE"
            },
            "properties" : {
              "name" : "system",
              "type" : "SSD",
              "size" : 5,
              "image" : "c1ffdd34-2e28-11e7-9888-525400f64d8d",
              "imagePassword" : null,
              "bus" : "VIRTIO",
              "licenceType" : "LINUX",
              "cpuHotPlug" : true,
              "cpuHotUnplug" : false,
              "ramHotPlug" : true,
              "ramHotUnplug" : false,
              "nicHotPlug" : true,
              "nicHotUnplug" : true,
              "discVirtioHotPlug" : true,
              "discVirtioHotUnplug" : true,
              "discScsiHotPlug" : false,
              "discScsiHotUnplug" : false,
              "deviceNumber" : 1
            }
          },
          "cpuFamily" : "AMD_OPTERON"
        },
        "entities" : {
          "cdroms" : {
            "id" : "7ca0bbc0-9458-44b8-9e97-0b8116f6940d/cdroms",
            "type" : "collection",
            "href" : "https://api.profitbricks.com/cloudapi/v3/datacenters/af583c3b-980a-4c28-9198-e9f5b79b6861/servers/7ca0bbc0-9458-44b8-9e97-0b8116f6940d/cdroms",
            "items" : [ ]
          },
          "volumes" : {
            "id" : "7ca0bbc0-9458-44b8-9e97-0b8116f6940d/volumes",
            "type" : "collection",
            "href" : "https://api.profitbricks.com/cloudapi/v3/datacenters/af583c3b-980a-4c28-9198-e9f5b79b6861/servers/7ca0bbc0-9458-44b8-9e97-0b8116f6940d/volumes",
            "items" : [ {
              "id" : "7fc9ab59-066d-43e1-99d3-d6d78b15143e",
              "type" : "volume",
              "href" : "https://api.profitbricks.com/cloudapi/v3/datacenters/af583c3b-980a-4c28-9198-e9f5b79b6861/volumes/7fc9ab59-066d-43e1-99d3-d6d78b15143e",
              "metadata" : {
                "createdDate" : "2017-06-05T23:09:56Z",
                "createdBy" : "jasmin@stackpointcloud.com",
                "etag" : "39fed922f2397227d436261f0f75d16c",
                "lastModifiedDate" : "2017-06-05T23:09:56Z",
                "lastModifiedBy" : "jasmin@stackpointcloud.com",
                "state" : "AVAILABLE"
              },
              "properties" : {
                "name" : "system",
                "type" : "SSD",
                "size" : 5,
                "availabilityZone" : "AUTO",
                "image" : "c1ffdd34-2e28-11e7-9888-525400f64d8d",
                "imagePassword" : null,
                "sshKeys" : null,
                "bus" : "VIRTIO",
                "licenceType" : "LINUX",
                "cpuHotPlug" : true,
                "cpuHotUnplug" : false,
                "ramHotPlug" : true,
                "ramHotUnplug" : false,
                "nicHotPlug" : true,
                "nicHotUnplug" : true,
                "discVirtioHotPlug" : true,
                "discVirtioHotUnplug" : true,
                "discScsiHotPlug" : false,
                "discScsiHotUnplug" : false,
                "deviceNumber" : 1
              }
            } ]
          },
          "nics" : {
            "id" : "7ca0bbc0-9458-44b8-9e97-0b8116f6940d/nics",
            "type" : "collection",
            "href" : "https://api.profitbricks.com/cloudapi/v3/datacenters/af583c3b-980a-4c28-9198-e9f5b79b6861/servers/7ca0bbc0-9458-44b8-9e97-0b8116f6940d/nics",
            "items" : [ {
              "id" : "4d50e806-5aab-4521-a9a9-2636f5733dab",
              "type" : "nic",
              "href" : "https://api.profitbricks.com/cloudapi/v3/datacenters/af583c3b-980a-4c28-9198-e9f5b79b6861/servers/7ca0bbc0-9458-44b8-9e97-0b8116f6940d/nics/4d50e806-5aab-4521-a9a9-2636f5733dab",
              "metadata" : {
                "createdDate" : "2017-06-05T23:11:28Z",
                "createdBy" : "jasmin@stackpointcloud.com",
                "etag" : "32e0dc4547250fccd1b955d6f7a863bf",
                "lastModifiedDate" : "2017-06-05T23:11:28Z",
                "lastModifiedBy" : "jasmin@stackpointcloud.com",
                "state" : "AVAILABLE"
              },
              "properties" : {
                "name" : null,
                "mac" : "02:01:dd:9a:77:bf",
                "ips" : [ "10.12.200.11" ],
                "dhcp" : false,
                "lan" : 2,
                "firewallActive" : true,
                "nat" : false
              },
              "entities" : {
                "firewallrules" : {
                  "id" : "4d50e806-5aab-4521-a9a9-2636f5733dab/firewallrules",
                  "type" : "collection",
                  "href" : "https://api.profitbricks.com/cloudapi/v3/datacenters/af583c3b-980a-4c28-9198-e9f5b79b6861/servers/7ca0bbc0-9458-44b8-9e97-0b8116f6940d/nics/4d50e806-5aab-4521-a9a9-2636f5733dab/firewallrules",
                  "items" : [ ]
                }
              }
            }, {
              "id" : "3263c8fd-7215-4bba-8d97-26308b55cf70",
              "type" : "nic",
              "href" : "https://api.profitbricks.com/cloudapi/v3/datacenters/af583c3b-980a-4c28-9198-e9f5b79b6861/servers/7ca0bbc0-9458-44b8-9e97-0b8116f6940d/nics/3263c8fd-7215-4bba-8d97-26308b55cf70",
              "metadata" : {
                "createdDate" : "2017-06-05T23:09:56Z",
                "createdBy" : "jasmin@stackpointcloud.com",
                "etag" : "39fed922f2397227d436261f0f75d16c",
                "lastModifiedDate" : "2017-06-05T23:09:56Z",
                "lastModifiedBy" : "jasmin@stackpointcloud.com",
                "state" : "AVAILABLE"
              },
              "properties" : {
                "name" : null,
                "mac" : "02:01:f6:8e:3f:4a",
                "ips" : [ "78.137.97.150" ],
                "dhcp" : true,
                "lan" : 1,
                "firewallActive" : false,
                "nat" : false
              },
              "entities" : {
                "firewallrules" : {
                  "id" : "3263c8fd-7215-4bba-8d97-26308b55cf70/firewallrules",
                  "type" : "collection",
                  "href" : "https://api.profitbricks.com/cloudapi/v3/datacenters/af583c3b-980a-4c28-9198-e9f5b79b6861/servers/7ca0bbc0-9458-44b8-9e97-0b8116f6940d/nics/3263c8fd-7215-4bba-8d97-26308b55cf70/firewallrules",
                  "items" : [ ]
                }
              }
            } ]
          }
        }
      } ]
    },
    "volumes" : {
      "id" : "af583c3b-980a-4c28-9198-e9f5b79b6861/volumes",
      "type" : "collection",
      "href" : "https://api.profitbricks.com/cloudapi/v3/datacenters/af583c3b-980a-4c28-9198-e9f5b79b6861/volumes",
      "items" : [ {
        "id" : "7fc9ab59-066d-43e1-99d3-d6d78b15143e",
        "type" : "volume",
        "href" : "https://api.profitbricks.com/cloudapi/v3/datacenters/af583c3b-980a-4c28-9198-e9f5b79b6861/volumes/7fc9ab59-066d-43e1-99d3-d6d78b15143e",
        "metadata" : {
          "createdDate" : "2017-06-05T23:09:56Z",
          "createdBy" : "jasmin@stackpointcloud.com",
          "etag" : "39fed922f2397227d436261f0f75d16c",
          "lastModifiedDate" : "2017-06-05T23:09:56Z",
          "lastModifiedBy" : "jasmin@stackpointcloud.com",
          "state" : "AVAILABLE"
        },
        "properties" : {
          "name" : "system",
          "type" : "SSD",
          "size" : 5,
          "availabilityZone" : "AUTO",
          "image" : "c1ffdd34-2e28-11e7-9888-525400f64d8d",
          "imagePassword" : null,
          "sshKeys" : null,
          "bus" : "VIRTIO",
          "licenceType" : "LINUX",
          "cpuHotPlug" : true,
          "cpuHotUnplug" : false,
          "ramHotPlug" : true,
          "ramHotUnplug" : false,
          "nicHotPlug" : true,
          "nicHotUnplug" : true,
          "discVirtioHotPlug" : true,
          "discVirtioHotUnplug" : true,
          "discScsiHotPlug" : false,
          "discScsiHotUnplug" : false,
          "deviceNumber" : 1
        }
      } ]
    },
    "loadbalancers" : {
      "id" : "af583c3b-980a-4c28-9198-e9f5b79b6861/loadbalancers",
      "type" : "collection",
      "href" : "https://api.profitbricks.com/cloudapi/v3/datacenters/af583c3b-980a-4c28-9198-e9f5b79b6861/loadbalancers",
      "items" : [ ]
    },
    "lans" : {
      "id" : "af583c3b-980a-4c28-9198-e9f5b79b6861/lans",
      "type" : "collection",
      "href" : "https://api.profitbricks.com/cloudapi/v3/datacenters/af583c3b-980a-4c28-9198-e9f5b79b6861/lans",
      "items" : [ {
        "id" : "2",
        "type" : "lan",
        "href" : "https://api.profitbricks.com/cloudapi/v3/datacenters/af583c3b-980a-4c28-9198-e9f5b79b6861/lans/2",
        "metadata" : {
          "createdDate" : "2017-06-05T23:11:28Z",
          "createdBy" : "jasmin@stackpointcloud.com",
          "etag" : "002cba1dd2f19be29505607da30b6f1b",
          "lastModifiedDate" : "2017-06-05T23:11:28Z",
          "lastModifiedBy" : "jasmin@stackpointcloud.com",
          "state" : "AVAILABLE"
        },
        "properties" : {
          "name" : "Lan 2",
          "public" : false
        },
        "entities" : {
          "nics" : {
            "id" : "2/nics",
            "type" : "collection",
            "href" : "https://api.profitbricks.com/cloudapi/v3/datacenters/af583c3b-980a-4c28-9198-e9f5b79b6861/lans/2/nics",
            "items" : [ {
              "id" : "4d50e806-5aab-4521-a9a9-2636f5733dab",
              "type" : "nic",
              "href" : "https://api.profitbricks.com/cloudapi/v3/datacenters/af583c3b-980a-4c28-9198-e9f5b79b6861/servers/7ca0bbc0-9458-44b8-9e97-0b8116f6940d/nics/4d50e806-5aab-4521-a9a9-2636f5733dab",
              "metadata" : {
                "createdDate" : "2017-06-05T23:11:28Z",
                "createdBy" : "jasmin@stackpointcloud.com",
                "etag" : "32e0dc4547250fccd1b955d6f7a863bf",
                "lastModifiedDate" : "2017-06-05T23:11:28Z",
                "lastModifiedBy" : "jasmin@stackpointcloud.com",
                "state" : "AVAILABLE"
              },
              "properties" : {
                "name" : null,
                "mac" : "02:01:dd:9a:77:bf",
                "ips" : [ "10.12.200.11" ],
                "dhcp" : false,
                "lan" : 2,
                "firewallActive" : true,
                "nat" : false
              },
              "entities" : {
                "firewallrules" : {
                  "id" : "4d50e806-5aab-4521-a9a9-2636f5733dab/firewallrules",
                  "type" : "collection",
                  "href" : "https://api.profitbricks.com/cloudapi/v3/datacenters/af583c3b-980a-4c28-9198-e9f5b79b6861/servers/7ca0bbc0-9458-44b8-9e97-0b8116f6940d/nics/4d50e806-5aab-4521-a9a9-2636f5733dab/firewallrules",
                  "items" : [ ]
                }
              }
            } ]
          }
        }
      }, {
        "id" : "1",
        "type" : "lan",
        "href" : "https://api.profitbricks.com/cloudapi/v3/datacenters/af583c3b-980a-4c28-9198-e9f5b79b6861/lans/1",
        "metadata" : {
          "createdDate" : "2017-06-05T23:09:44Z",
          "createdBy" : "jasmin@stackpointcloud.com",
          "etag" : "f4ebd6eaa6ed61ca312ec206d95d38fa",
          "lastModifiedDate" : "2017-06-05T23:09:44Z",
          "lastModifiedBy" : "jasmin@stackpointcloud.com",
          "state" : "AVAILABLE"
        },
        "properties" : {
          "name" : "public",
          "public" : true
        },
        "entities" : {
          "nics" : {
            "id" : "1/nics",
            "type" : "collection",
            "href" : "https://api.profitbricks.com/cloudapi/v3/datacenters/af583c3b-980a-4c28-9198-e9f5b79b6861/lans/1/nics",
            "items" : [ {
              "id" : "3263c8fd-7215-4bba-8d97-26308b55cf70",
              "type" : "nic",
              "href" : "https://api.profitbricks.com/cloudapi/v3/datacenters/af583c3b-980a-4c28-9198-e9f5b79b6861/servers/7ca0bbc0-9458-44b8-9e97-0b8116f6940d/nics/3263c8fd-7215-4bba-8d97-26308b55cf70",
              "metadata" : {
                "createdDate" : "2017-06-05T23:09:56Z",
                "createdBy" : "jasmin@stackpointcloud.com",
                "etag" : "39fed922f2397227d436261f0f75d16c",
                "lastModifiedDate" : "2017-06-05T23:09:56Z",
                "lastModifiedBy" : "jasmin@stackpointcloud.com",
                "state" : "AVAILABLE"
              },
              "properties" : {
                "name" : null,
                "mac" : "02:01:f6:8e:3f:4a",
                "ips" : [ "78.137.97.150" ],
                "dhcp" : true,
                "lan" : 1,
                "firewallActive" : false,
                "nat" : false
              },
              "entities" : {
                "firewallrules" : {
                  "id" : "3263c8fd-7215-4bba-8d97-26308b55cf70/firewallrules",
                  "type" : "collection",
                  "href" : "https://api.profitbricks.com/cloudapi/v3/datacenters/af583c3b-980a-4c28-9198-e9f5b79b6861/servers/7ca0bbc0-9458-44b8-9e97-0b8116f6940d/nics/3263c8fd-7215-4bba-8d97-26308b55cf70/firewallrules",
                  "items" : [ ]
                }
              }
            } ]
          }
        }
      } ]
    }
  }
}
```
